### ISSUE TITLE
Problema com a alteração da fonte

### ISSUE THREAD

**Issue by josualdo188** [josualdo188/pokedex#2]
@npsouza
Não estou conseguindo altera a fonte,  eu baixei e coloquei em uma pasta, mas não ta funciando

https://github.com/josualdo188/pokedex/blob/b05635c53ae0e34dce3adbeb8ea1cd9dfa405327/css/style.css

**Comment by npsouza** [comment]
@josualdo188 tem 2 `font-family` ali, só o último está sendo considerado.

https://github.com/josualdo188/pokedex/blob/b05635c53ae0e34dce3adbeb8ea1cd9dfa405327/css/style.css#L6-L12
